import { test, expect } from '@playwright/test';
import { mkdirSync } from 'node:fs';

test('complete review experience, rendered math, persistence, responsive layout and themes', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  mkdirSync('test-results/screenshots', { recursive: true });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Your next chapter starts here.' })).toBeVisible();
  await expect(page.getByText(/Our deepest fear is not that we are inadequate/)).toBeVisible();
  await page.screenshot({ path: 'test-results/screenshots/home-light.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Try starter references' }).click();
  await expect(page.getByRole('button', { name: /PSAD · Starter reference/ })).toBeVisible();
  await page.getByRole('button', { name: 'Concepts & Formulas', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Angle of friction', exact: true })).toBeVisible();
  await expect(page.locator('.math-error')).toHaveCount(0);
  const formula = page.locator('.formula-card').filter({ has: page.getByRole('heading', { name: 'Angle of friction', exact: true }) });
  await expect(formula.locator('.katex-mathml')).toContainText(['θ']);
  await page.getByRole('button', { name: 'Edit Angle of friction', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.locator('.equation-preview .katex')).toBeVisible();
  await page.getByRole('button', { name: 'Save formula', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.screenshot({ path: 'test-results/screenshots/formulas-light.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Practice', exact: true }).click();
  await page.getByRole('button', { name: 'Generate new questions', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Generate new questions', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.problem-panel h2')).toHaveText(/Angle of friction|Average normal stress/);
  await expect(page.locator('.engineering-diagram')).toBeVisible();
  await page.getByLabel('Your answer').fill('-999');
  await page.getByRole('button', { name: 'Check answer', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'A useful step in learning.' })).toBeVisible();
  await expect(page.locator('.solution-step')).toHaveCount(2);
  await page.screenshot({ path: 'test-results/screenshots/practice-light.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Flashcards', exact: true }).click();
  await page.getByRole('button', { name: 'Equations', exact: true }).click();
  await page.getByRole('button', { name: 'Reveal flashcard answer', exact: true }).click();
  await expect(page.locator('.flashcard .katex')).not.toHaveCount(0);
  await page.getByRole('button', { name: 'Good Spaced review', exact: true }).click();
  await page.getByRole('button', { name: 'Progress', exact: true }).click();
  await expect(page.locator('.progress-stat').filter({ hasText: 'Problems attempted' }).locator('strong')).toHaveText('1');
  await page.screenshot({ path: 'test-results/screenshots/progress-light.png', fullPage: true, animations: 'disabled' });
  await page.reload();
  await page.getByRole('button', { name: 'Progress', exact: true }).click();
  await expect(page.locator('.progress-stat').filter({ hasText: 'Flashcard reviews' }).locator('strong')).toHaveText('1');
  await page.getByRole('button', { name: 'Switch to dark mode' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('button', { name: 'Home', exact: false }).first().click();
  await page.screenshot({ path: 'test-results/screenshots/home-dark.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Concepts & Formulas', exact: true }).click();
  await page.screenshot({ path: 'test-results/screenshots/formulas-dark.png', fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Open navigation', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click();
  await page.getByRole('button', { name: 'Home', exact: false }).first().click();
  await expect(page.getByRole('heading', { name: 'Your next chapter starts here.' })).toBeVisible();
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/screenshots/home-mobile-dark.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: /Upload files$/ }).click();
  await page.locator('input[type=file]').setInputFiles([{ name: 'PSAD Set 2.txt', mimeType: 'text/plain', buffer: Buffer.from('Angle of friction: tan(theta) = f/N.\nNormal reaction N is in newtons.') }, { name: 'Extra notes.txt', mimeType: 'text/plain', buffer: Buffer.from('Equilibrium: sum of forces = 0.') }]);
  await page.getByLabel('Set number', { exact: true }).fill('2');
  await page.getByRole('dialog').getByRole('button', { name: 'Upload 2 files', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByLabel('Filter by set', { exact: true }).selectOption('2');
  await expect(page.getByRole('button', { name: /PSAD Set 2.txt/ })).toBeVisible();
  await expect(page.getByRole('button', { name: /Starter reference/ })).toHaveCount(0);
  await page.getByRole('button', { name: /PSAD Set 2.txt/ }).click();
  await page.getByRole('button', { name: 'Extract all pages with AI', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Add a Gemini API key' })).toBeVisible();
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click();
  expect(errors).toEqual([]);
});
