import test, { before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { PDFDocument } from 'pdf-lib';

const directory = mkdtempSync(path.join(os.tmpdir(), 'civinco-api-'));
const port = 14173;
let processHandle;
async function api(url, body, method) {
  const response = await fetch(`http://127.0.0.1:${port}/api${url}`, { method: method || (body ? 'POST' : 'GET'), headers: body instanceof FormData ? {} : { 'Content-Type': 'application/json' }, body: body ? body instanceof FormData ? body : JSON.stringify(body) : undefined });
  return { status: response.status, data: await response.json() };
}
async function start() {
  processHandle = spawn(process.execPath, ['server/index.mjs', '--production'], { env: { ...process.env, PORT: String(port), CIVINCO_DATA_DIR: directory, GEMINI_API_KEY: '', SUPABASE_URL: '', SUPABASE_SECRET_KEY: '', SUPABASE_SERVICE_ROLE_KEY: '', CIVINCO_ACCESS_PASSWORD: '', CIVINCO_SESSION_SECRET: 'api-test-secret' }, stdio: ['ignore', 'pipe', 'pipe'], windowsHide: true });
  await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Server startup timed out')), 15000);
    processHandle.once('error', reject);
    processHandle.stdout.on('data', chunk => { if (chunk.toString().includes('is ready')) { clearTimeout(timer); resolve(); } });
    processHandle.once('exit', code => { clearTimeout(timer); reject(new Error(`Server exited ${code}`)); });
  });
}
async function stop() { if (processHandle && processHandle.exitCode === null) await new Promise(resolve => { processHandle.once('exit', resolve); processHandle.kill(); }); }
before(start);
after(async () => { await stop(); rmSync(directory, { recursive: true, force: true }); });
test('full local study workflow, source coverage, grading, review gates, persistence and deletion', async () => {
  assert.equal((await api('/state')).data.settings.connected, false);
  await api('/samples', {});
  let state = (await api('/state')).data;
  assert.equal(state.documents.length, 3);
  const generation = await api('/questions/generate', { spex: 'A', set: 1, mode: 'sample', count: 3, difficulty: 'Foundation' });
  assert.equal(generation.status, 200);
  const q = generation.data.questions[0];
  assert.equal('answer' in q, false); assert.equal('steps' in q, false);
  const invalid = await api(`/questions/${q.id}/answer`, { answer: 'abc' });
  assert.equal(invalid.status, 400);
  const wrong = await api(`/questions/${q.id}/answer`, { answer: '-999' });
  assert.equal(wrong.data.correct, false);
  const right = await api(`/questions/${q.id}/answer`, { answer: String(wrong.data.expected) });
  assert.equal(right.status, 409);
  state = (await api('/state')).data;
  assert.equal(state.attempts.length, 1); assert.equal(state.attempts[0].correct, false);
  await api(`/questions/${generation.data.questions[1].id}/solution`, {});
  const review = await api('/reviews', { itemId: state.items[0].id, rating: 'good' });
  assert.equal(review.status, 200);
  const form = new FormData();
  form.append('spex', 'B'); form.append('set', '3'); form.append('kind', 'Book');
  const pdf = await PDFDocument.create(); pdf.addPage(); pdf.addPage();
  form.append('files', new Blob([await pdf.save()], { type: 'application/pdf' }), 'two-pages.pdf');
  const sourceText = 'Equilibrium: \\sum F_x = 0.\n'.repeat(1300);
  form.append('files', new Blob([sourceText], { type: 'text/plain' }), 'long-notes.txt');
  const uploaded = await api('/documents', form);
  assert.equal(uploaded.status, 201); assert.equal(uploaded.data.accepted.length, 2);
  const doc = uploaded.data.accepted[0];
  assert.equal(doc.totalPages, 2); assert.equal(doc.spex, 'B'); assert.equal(doc.set, 3);
  assert.equal(uploaded.data.accepted[1].totalPages, Math.ceil(sourceText.length / 12000));
  state = (await api('/state')).data;
  assert.equal(state.pages.filter(p => p.docId === doc.id).length, 2);
  assert.ok(state.documents.every(d => !('storageName' in d)));
  const blockedExtraction = await api(`/documents/${doc.id}/extract`, {});
  assert.equal(blockedExtraction.status, 409);
  const bankForm = new FormData();
  bankForm.append('file', new Blob([JSON.stringify({ version: 1, name: 'Permanent PSAD Bank', spex: 'A', set: 7, questions: [{ title: 'Imported force problem', topic: 'Statics', prompt: 'A 12 N horizontal force acts on a body. Determine the force magnitude.', answer: 12, unit: 'N', tolerance: 0.01, steps: [{ text: 'Read the stated magnitude.', latex: 'F=12\\ \\mathrm{N}' }] }] })], { type: 'application/json' }), 'bank.json');
  const bankImport = await api('/problem-banks', bankForm);
  assert.equal(bankImport.status, 201); assert.equal(bankImport.data.imported, 1); assert.equal(bankImport.data.skipped, 0);
  const bankDoc = bankImport.data.document, bankQuestion = bankImport.data.questions[0];
  assert.equal(bankQuestion.mode, 'bank'); assert.equal('answer' in bankQuestion, false); assert.equal(bankQuestion.sourceDocId, bankDoc.id);
  state = (await api('/state')).data;
  assert.equal(state.questions.some(question => question.id === bankQuestion.id), false);
  const guideProblems = await api('/guide/problems?spex=A&set=7');
  assert.equal(guideProblems.status, 200); assert.equal(guideProblems.data.questions.length, 1); assert.equal('answer' in guideProblems.data.questions[0], false);
  const openedGuideProblem = await api(`/guide/problems/${bankQuestion.id}/open`, { replace: true });
  assert.equal(openedGuideProblem.status, 200); assert.notEqual(openedGuideProblem.data.question.id, bankQuestion.id);
  const unconfirmedGuideReplacement = await api(`/guide/problems/${bankQuestion.id}/open`, {});
  assert.equal(unconfirmedGuideReplacement.status, 409);
  const confirmedGuideReplacement = await api(`/guide/problems/${bankQuestion.id}/open`, { replace: true });
  assert.equal(confirmedGuideReplacement.status, 200);
  const unconfirmedReplacement = await api('/questions/generate', { spex: 'A', set: 7, mode: 'bank', count: 1, difficulty: 'Foundation' });
  assert.equal(unconfirmedReplacement.status, 409);
  const bankDraw = await api('/questions/generate', { spex: 'A', set: 7, mode: 'bank', count: 1, difficulty: 'Foundation', replace: true });
  assert.equal(bankDraw.status, 200); assert.equal(bankDraw.data.questions.length, 1);
  const bankSessionQuestion = bankDraw.data.questions[0];
  assert.equal(bankSessionQuestion.mode, 'bank'); assert.notEqual(bankSessionQuestion.id, bankQuestion.id);
  assert.match((await fetch(`http://127.0.0.1:${port}/api/problem-banks/template`)).headers.get('content-type'), /application\/json/);
  const pixel = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M/wHwAF/gL+XwVdWQAAAABJRU5ErkJggg==';
  const imageBankForm = new FormData();
  imageBankForm.append('file', new Blob([JSON.stringify({ version: 1, name: 'Ordered illustrated bank', spex: 'A', set: 8, questions: [
    { title: 'First member', topic: 'Trusses', prompt: 'Using the shown truss, determine member 1.', answer: 1, unit: 'kN', tolerance: 0.01, steps: [{ text: 'Source answer.', latex: '' }], diagramImage: { data: pixel, alt: 'Source truss diagram', caption: 'Shared figure.' } },
    { title: 'Second member', topic: 'Trusses', prompt: 'Using the shown truss, determine member 2.', answer: 2, unit: 'kN', tolerance: 0.01, steps: [{ text: 'Source answer.', latex: '' }], diagramImage: { data: pixel, alt: 'Source truss diagram', caption: 'Shared figure.' } },
  ] })], { type: 'application/json' }), 'illustrated-bank.json');
  const imageBank = await api('/problem-banks', imageBankForm);
  assert.equal(imageBank.status, 201); assert.deepEqual(imageBank.data.questions.map(question => question.sourcePage), [1, 2]);
  assert.ok(imageBank.data.questions.every(question => question.diagram.image.url.endsWith('/diagram')));
  const sourceDiagram = await fetch(`http://127.0.0.1:${port}${imageBank.data.questions[1].diagram.image.url}`);
  assert.equal(sourceDiagram.status, 200); assert.match(sourceDiagram.headers.get('content-type'), /image\/png/);
  const multiSetDraw = await api('/questions/generate', { spex: 'A', sets: [7, 8], mode: 'bank', count: 3, difficulty: 'Foundation', replace: true });
  assert.equal(multiSetDraw.status, 200); assert.equal(multiSetDraw.data.questions.length, 3);
  assert.deepEqual([...new Set(multiSetDraw.data.questions.map(question => question.set))], [7, 8]);
  const retainedMultiSetQuestion = multiSetDraw.data.questions.find(question => question.set === 7);
  assert.equal((await api(`/questions/${retainedMultiSetQuestion.id}/report`, { category: 'solution', note: 'Check the worked result.' })).status, 201);
  assert.equal((await api(`/questions/${retainedMultiSetQuestion.id}/report`, { category: 'units', note: 'Check the displayed unit.' })).status, 200);
  assert.equal((await api(`/documents/${imageBank.data.document.id}`, undefined, 'DELETE')).status, 200);
  assert.equal((await api(`/documents/${doc.id}/pages/1/review`, {})).status, 400);
  const newFormula = { docId: doc.id, page: 1, title: 'Force balance', topic: 'Statics', latex: String.raw`\sum F_x = 0`, variables: [{ symbol: 'F_x', meaning: 'Horizontal force component', unit: 'N' }], conditions: 'Static equilibrium', uncertain: false, note: '', reviewed: true };
  assert.equal((await api('/items', newFormula)).status, 201);
  assert.equal((await api('/items', { ...newFormula, latex: String.raw`\frac{` })).status, 400);
  assert.equal((await api('/items', { ...newFormula, page: 3 })).status, 400);
  assert.equal((await api(`/documents/${doc.id}`, { spex: 'C', set: 4 }, 'PATCH')).status, 200);
  state = (await api('/state')).data;
  assert.equal(state.items.find(i => i.docId === doc.id).spex, 'C');
  const fetched = await fetch(`http://127.0.0.1:${port}/api/documents/${doc.id}/source`);
  assert.match(fetched.headers.get('content-type'), /application\/pdf/);
  const badForm = new FormData(); badForm.append('spex', 'A'); badForm.append('set', '1'); badForm.append('files', new Blob(['not a pdf']), 'bad.pdf');
  assert.equal((await api('/documents', badForm)).status, 400);
  await stop(); await start();
  state = (await api('/state')).data;
  assert.equal(state.documents.length, 6); assert.equal(state.attempts.length, 2); assert.equal(state.reviews.length, 1);
  assert.equal(state.questions.some(question => question.id === bankQuestion.id), false);
  assert.equal(state.questions.some(question => question.id === retainedMultiSetQuestion.id && question.mode === 'bank'), true);
  assert.equal((await api(`/documents/${bankDoc.id}`, undefined, 'DELETE')).status, 200);
  state = (await api('/state')).data;
  assert.equal(state.questions.some(question => question.id === bankQuestion.id), false);
  assert.equal((await api(`/documents/${doc.id}`, undefined, 'DELETE')).status, 200);
  state = (await api('/state')).data;
  assert.equal(state.pages.some(p => p.docId === doc.id), false); assert.equal(state.items.some(i => i.docId === doc.id), false);
});
test('reject cross-origin mutations and invalid categories', async () => {
  const response = await fetch(`http://127.0.0.1:${port}/api/samples`, { method: 'POST', headers: { Origin: 'https://unrelated.example' } });
  assert.equal(response.status, 403);
  const form = new FormData(); form.append('spex', 'Z'); form.append('set', '0'); form.append('files', new Blob(['x']), 'notes.txt');
  assert.equal((await api('/documents', form)).status, 400);
});
