import { useState } from 'react';
import { ArrowRight, BookMarked, BookOpen, ChevronRight, FileText, FolderOpen, Layers, RefreshCw, Search, ShieldCheck, Sparkles, Upload, Waves, Triangle, Ruler } from 'lucide-react';
import { api, Badge, Empty, Status } from './components';
import { SPEX, type Source, type Spex, type View } from './types';
import type { SharedProps } from './App';

export function Home({ state, filter, search, setSearch, onUpload, onSource, navigate, onSpex, onSettings, refresh, notify }: SharedProps & { search: string; setSearch: (s: string) => void; onUpload: () => void; onSource: (doc: Source) => void; navigate: (v: View) => void; onSpex: (s: Spex) => void; onSettings: () => void }) {
  const [busy, setBusy] = useState(false), [refreshing, setRefreshing] = useState(false), [error, setError] = useState('');
  const docs = filter(state.documents).filter(d => d.name.toLowerCase().includes(search.toLowerCase()));
  const items = filter(state.items), formulas = items.filter(i => i.kind === 'formula');
  const pages = state.pages.filter(p => filter(state.documents).some(d => d.id === p.docId));
  const reviewed = pages.filter(p => p.reviewed).length;
  const samples = state.documents.some(d => d.sample);
  const uploaded = state.documents.filter(d => !d.sample && d.editable !== false);
  const unfinished = uploaded.filter(d => state.pages.some(p => p.docId === d.id && p.status !== 'extracted')).length;
  async function seed() { setBusy(true); setError(''); try { await api('/samples', {}); await refresh(); notify('Starter references added. Your uploaded course materials stay separate.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function refreshAll() { setRefreshing(true); setError(''); try { const result = await api<{ queued: number; skipped: number }>('/documents/extract-all', {}); await refresh(); notify(result.queued ? `${result.queued} file${result.queued === 1 ? '' : 's'} queued for Gemini.` : 'Extraction is already up to date.'); } catch (e) { setError((e as Error).message); } finally { setRefreshing(false); } }
  return <>
    <div className="home-grid"><section className="hero-panel"><div className="hero-copy"><div className="pill"><span /> CIVIL ENGINEERING REVIEW</div><h2>Review.<br />Practice. Repeat.</h2><blockquote>“Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure...”</blockquote><button className="button hero-button" onClick={() => navigate('practice')}>Open practice <ArrowRight size={16} /></button></div><div className="blueprint" aria-hidden="true"><svg viewBox="0 0 300 230"><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M 20 0 L 0 0 0 20" fill="none" stroke="currentColor" strokeWidth=".4" opacity=".35" /></pattern></defs><rect width="300" height="230" fill="url(#grid)" /><g fill="none" stroke="currentColor" strokeWidth="1.3"><path d="M25 170H275M45 170V110L150 48l105 62v60M45 110h210M70 170v-60l80-62 80 62v60M100 170v-60l50-62 50 62v60M150 48v122M45 110l55 60 50-60 50 60 55-60M25 188h250M45 182v12m210-12v12" /><circle cx="150" cy="48" r="5" /><circle cx="45" cy="110" r="4" /><circle cx="255" cy="110" r="4" /></g><g fontFamily="serif" fontStyle="italic" fill="currentColor"><text x="202" y="51" fontSize="17">ΣF = 0</text><text x="126" y="209" fontSize="14">L</text><text x="16" y="89" fontSize="17">θ</text></g></svg></div></section>
      <section className="session-panel"><div className="section-kicker"><BookOpen size={16} /> CONTINUE</div><h3>Continue studying</h3>{[{ icon: BookMarked, title: 'Study guide', detail: 'Learn topics in a useful order', view: 'guide' }, { icon: BookOpen, title: 'Concepts & formulas', detail: 'Review extracted material', view: 'library' }, { icon: Layers, title: 'Flashcards', detail: 'Run a recall session', view: 'flashcards' }].map(({ icon: Icon, title, detail, view }) => <button className="toolkit-link" key={view} onClick={() => navigate(view as View)}><span className="toolkit-icon"><Icon size={19} /></span><span><strong>{title}</strong><small>{detail}</small></span><ChevronRight size={17} /></button>)}</section></div>
    <div className="stats-strip">{[{ icon: FolderOpen, number: filter(state.documents).filter(d => !d.sample).length, label: 'Files in your library', hint: `${filter(state.documents).filter(d => d.sample).length} starter references` }, { icon: BookOpen, number: formulas.length, label: 'Equations collected', hint: `${formulas.filter(f => f.reviewed).length} checked formulas` }, { icon: Layers, number: items.length, label: 'Available flashcards', hint: 'Concepts + equations' }, { icon: ShieldCheck, number: `${reviewed}/${pages.length}`, label: 'Source pages reviewed', hint: 'Track extraction coverage' }].map(({ icon: Icon, number, label, hint }) => <div className="stat" key={label}><span className="stat-icon"><Icon size={19} /></span><div><strong>{number}</strong><span>{label}</span><small>{hint}</small></div></div>)}</div>
    <div className="section-title"><h2>Your examinations</h2></div>
    <div className="subject-cards">{(Object.entries(SPEX) as [Spex, typeof SPEX.A][]).map(([key, s], index) => {
      const Icon = [Triangle, Ruler, Waves][index], files = state.documents.filter(d => d.spex === key && !d.sample), sets = new Set(state.documents.filter(d => d.spex === key).map(d => d.set));
      return <button key={key} className={`subject-card ${s.color}`} onClick={() => onSpex(key)}><div className="subject-card-top"><span className="subject-icon"><Icon size={23} strokeWidth={1.5} /></span><span>SPEX {key}</span><ArrowRight size={17} /></div><h3>{s.code}</h3><p>{s.short}</p><div className="subject-card-bottom"><span><FolderOpen size={13} /> {files.length} {files.length === 1 ? 'file' : 'files'}</span><span>{sets.size} {sets.size === 1 ? 'set' : 'sets'}</span></div></button>;
    })}</div>
    <section className="file-library"><div className="section-title"><h2>Your library <span className="count-bubble">{docs.length}</span></h2><div className="library-heading-actions">{!!uploaded.length && <button className="button secondary" disabled={refreshing || !unfinished} onClick={refreshAll}>{refreshing ? <RefreshCw className="spin" size={15} /> : <RefreshCw size={15} />} {unfinished ? `Refresh extraction (${unfinished})` : 'Extraction up to date'}</button>}<label className="search-box"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search files…" aria-label="Search files" /></label></div></div>
      {docs.length ? <div className="file-table"><div className="file-table-head"><span>FILE NAME</span><span>EXAMINATION</span><span>STATUS</span><span /></div>{docs.sort((a, b) => b.createdAt.localeCompare(a.createdAt)).map(doc => {
        const extracted = state.pages.filter(p => p.docId === doc.id && p.status === 'extracted').length;
        const label = doc.sample ? 'Starter reference' : doc.status === 'extracted' ? 'Ready to review' : doc.status === 'extracting' ? `Extracting ${extracted}/${doc.totalPages}` : doc.status === 'partial' ? 'Needs retry' : doc.status === 'stored' ? 'Ready to extract' : doc.status[0].toUpperCase() + doc.status.slice(1);
        return <button className="file-row" key={doc.id} onClick={() => onSource(doc)}><span className="file-info"><span className={`file-icon ${doc.sample ? 'sample' : ''}`}><FileText size={21} /></span><span><strong>{doc.name}</strong><small>{doc.kind} · {doc.sample ? 'Included example' : `${doc.totalPages} ${doc.extension === '.json' ? 'problems' : ['.txt', '.md'].includes(doc.extension || '') ? 'sections' : 'pages'} · ${doc.size > 1e6 ? (doc.size / 1e6).toFixed(1) + ' MB' : Math.ceil(doc.size / 1000) + ' KB'}`}</small></span></span>{doc.autoCategorize && !doc.categoryDetected ? <span className="badge">AUTO · PENDING</span> : <Badge spex={doc.spex} set={doc.set} />}<span className={`file-status ${doc.status === 'extracting' ? 'working' : ''}`}><span />{label}</span><ChevronRight size={16} /></button>;
      })}</div> : search ? <Empty icon={<Search />} title="No matching files" text="Try another filename or change your SPEX and Set filters." /> : <button className="upload-empty" onClick={onUpload}><span className="upload-circle"><Upload size={24} /></span><strong>Your study space is ready.</strong><span>Upload your first module or book to make it yours.</span><small>PDF, PNG, JPG, TXT, MD · Up to 50 MB per file</small><span className="button secondary">+ Add your first files</span></button>}
    </section>
    {error && <Status>{error}</Status>}
    {!samples && <div className="starter-banner"><span className="starter-icon"><BookOpen size={21} /></span><div><strong>Open the starter references.</strong><p>Explore clearly labeled formulas, flashcards, and practice questions.</p></div><button className="text-button" disabled={busy} onClick={seed}>{busy ? 'Adding…' : 'Add starter references'} <ArrowRight size={16} /></button></div>}
    {!state.settings.connected && <div className="connection-banner"><span><span className="connection-dot" /> Connect Gemini to classify files, extract equations, and generate practice.</span><button className="text-button" onClick={onSettings}>Connect Gemini <ArrowRight size={14} /></button></div>}
  </>;
}
