import { Fragment, useState } from 'react';
import { BookOpen, Check, CheckCircle2, ExternalLink, LoaderCircle, Pencil, Plus, Search, Sigma, Trash2 } from 'lucide-react';
import { api, Badge, Empty, MathText, Modal, normalizeEngineeringText, RichText, SourceLink, Status } from './components';
import { categoryPosition, compareByPdfOrder, sourceCategory } from './studyCategories';
import { type Item, type Source, type Variable } from './types';
import type { SharedProps } from './App';

export function Library({ state, filter, search, setSearch, refresh, notify }: SharedProps & { search: string; setSearch: (s: string) => void }) {
  const [tab, setTab] = useState('formula'), [review, setReview] = useState('all'), [category, setCategory] = useState('all'), [editing, setEditing] = useState<Item | null>(null);
  const [repairing, setRepairing] = useState(''), [repairingAll, setRepairingAll] = useState(false), [repairError, setRepairError] = useState('');
  const documentOrder = new Map(state.documents.map((document, index) => [document.id, index]));
  const all = filter(state.items).sort((a, b) => categoryPosition(sourceCategory(a, state.documents)) - categoryPosition(sourceCategory(b, state.documents)) || sourceCategory(a, state.documents).localeCompare(sourceCategory(b, state.documents)) || compareByPdfOrder(a, b, documentOrder));
  const categories = [...new Set(all.filter(i => i.kind === tab).map(i => sourceCategory(i, state.documents)))].sort((a, b) => categoryPosition(a) - categoryPosition(b) || a.localeCompare(b));
  const items = all.filter(i => i.kind === tab && (review === 'all' || !i.reviewed || i.uncertain) && (category === 'all' || !categories.includes(category) || sourceCategory(i, state.documents) === category) && `${i.title} ${i.topic} ${i.latex || ''} ${i.explanation || ''}`.toLowerCase().includes(search.toLowerCase()));
  const needsHelp = (item: Item) => Boolean(item.uncertain || !item.variables?.length || item.variables.some(variable => !variable.meaning.trim() || /not defined|unknown|unclear|illegible|unreadable|missing/i.test(variable.meaning)));
  const missing = state.items.filter(item => item.kind === 'formula' && item.editable !== false && !item.sample && needsHelp(item));
  async function repair(item: Item) {
    setRepairing(item.id); setRepairError('');
    try {
      const result = await api<{ suggestion: Partial<Item>; confidence: 'high' | 'medium' | 'low'; reason: string; sources: { title: string; url: string }[]; searchEntryPoint: string }>(`/items/${item.id}/repair`, {});
      setEditing({ ...item, ...result.suggestion, reviewed: false, webSources: result.sources, repairConfidence: result.confidence, repairReason: result.reason, searchEntryPoint: result.searchEntryPoint });
    } catch (error) { setRepairError((error as Error).message); }
    finally { setRepairing(''); }
  }
  async function repairAllMissing() {
    setRepairingAll(true); setRepairError('');
    try {
      const result = await api<{ repaired: number; failed: number; errors: { title: string; error: string }[] }>('/items/repair-missing', { itemIds: missing.map(item => item.id) });
      await refresh();
      notify(`${result.repaired} equation${result.repaired === 1 ? '' : 's'} updated with missing details.${result.failed ? ` ${result.failed} could not be completed.` : ''}`);
      if (result.errors.length) setRepairError(result.errors.map(error => `${error.title}: ${error.error}`).join('\n'));
    } catch (error) { setRepairError((error as Error).message); }
    finally { setRepairingAll(false); }
  }
  return <><div className="library-toolbar"><div className="segmented"><button className={tab === 'formula' ? 'active' : ''} onClick={() => { setTab('formula'); setCategory('all'); }}><Sigma size={17} /> Formulas <span>{all.filter(i => i.kind === 'formula').length}</span></button><button className={tab === 'concept' ? 'active' : ''} onClick={() => { setTab('concept'); setCategory('all'); }}><BookOpen size={16} /> Concepts <span>{all.filter(i => i.kind === 'concept').length}</span></button></div><label className="search-box"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder={`Search ${tab === 'formula' ? 'equations' : 'concepts'}…`} aria-label="Search study entries" /></label></div>
    <div className="library-subtoolbar"><span>{items.length} {tab === 'formula' ? 'equations' : 'concepts'} in your selection</span><div>{tab === 'formula' && missing.length > 0 && <button className="button secondary" disabled={repairingAll || Boolean(repairing)} onClick={repairAllMissing}>{repairingAll ? <LoaderCircle className="spin" size={14} /> : <Search size={14} />}{repairingAll ? 'Finding details…' : `Find all missing details (${missing.length})`}</button>}<select aria-label="Filter by slide category" value={categories.includes(category) ? category : 'all'} onChange={e => setCategory(e.target.value)}><option value="all">All slide categories</option>{categories.map(value => <option key={value}>{value}</option>)}</select>{tab === 'formula' && <select aria-label="Filter by review status" value={review} onChange={e => setReview(e.target.value)}><option value="all">All review statuses</option><option value="needs-review">Needs review</option></select>}</div></div>
    {repairError && <Status>{repairError}</Status>}
    {!items.length ? <Empty icon={tab === 'formula' ? <Sigma size={28} /> : <BookOpen size={28} />} title={`No ${tab === 'formula' ? 'formulas' : 'concepts'} here yet`} text="Upload and extract your materials from Home, add starter references, or adjust your filters." /> : <div className="formula-grid">{items.map((item, index) => <Fragment key={item.id}>{(index === 0 || sourceCategory(items[index - 1], state.documents) !== sourceCategory(item, state.documents)) && <div className="library-category-heading"><span>SOURCE PDF SECTION</span><h2>{sourceCategory(item, state.documents)}</h2></div>}<article className={`formula-card ${item.uncertain ? 'uncertain' : ''}`} key={item.id}><div className="formula-card-top"><Badge spex={item.spex} set={item.set} />{item.kind === 'formula' && item.editable !== false && <div className="formula-card-actions">{!item.sample && <button className="button tiny secondary" disabled={Boolean(repairing)} onClick={() => repair(item)}>{repairing === item.id ? <LoaderCircle className="spin" size={14} /> : <Search size={14} />}{needsHelp(item) ? 'Find missing details' : 'Check online'}</button>}<button className="icon-button" aria-label={`Edit ${item.title}`} onClick={() => setEditing(item)}><Pencil size={15} /></button></div>}</div><span className="topic-label">{item.topic}</span><h3>{item.title}</h3>{item.kind === 'formula' ? <><div className="equation-display"><MathText latex={item.latex || ''} block contextDiagram /></div><div className="variable-list">{item.variables?.map((v, n) => <div key={n}><span><MathText latex={v.symbol} /></span><span>{v.meaning}{v.unit && <small>{normalizeEngineeringText(v.unit)}</small>}</span></div>)}</div>{item.conditions && <p className="conditions"><strong>Applies when</strong> {item.conditions}</p>}{item.note && <p className="formula-note">{item.note}</p>}{item.webSources?.length ? <div className="web-source-summary"><strong>Reference checked online</strong><span>{item.webSources.length} cited {item.webSources.length === 1 ? 'source' : 'sources'}</span></div> : null}<div className={`review-indicator ${item.reviewed && !item.uncertain ? 'checked' : ''}`}>{item.reviewed && !item.uncertain ? <><CheckCircle2 size={13} /> {item.sample ? 'Starter formula' : 'Checked by you'}</> : <><span /> {item.uncertain ? 'Uncertain notation · check source' : 'Needs source review'}</>}</div></> : <p className="concept-text"><RichText text={item.explanation || ''} /></p>}<SourceLink doc={state.documents.find(d => d.id === item.docId)} page={item.page} /></article></Fragment>)}</div>}
    {editing && <FormulaEditor item={editing} documents={state.documents.filter(document => document.editable !== false)} onClose={() => setEditing(null)} onSaved={async () => { await refresh(); setEditing(null); notify('Equation and variable definitions saved.'); }} />}
  </>;
}

export function FormulaEditor({ item, documents, onClose, onSaved }: { item?: Item; documents: Source[]; onClose: () => void; onSaved: () => Promise<void> }) {
  const [title, setTitle] = useState(item?.title || ''), [topic, setTopic] = useState(item?.topic || ''), [latex, setLatex] = useState(item?.latex || String.raw`\tan\theta = \frac{f}{N}`);
  const [variables, setVariables] = useState<Variable[]>(item?.variables || [{ symbol: String.raw`\theta`, meaning: 'Angle of friction', unit: '°' }, { symbol: 'f', meaning: 'Limiting friction force', unit: 'N' }, { symbol: 'N', meaning: 'Normal reaction force', unit: 'N' }]);
  const [conditions, setConditions] = useState(item?.conditions || ''), [note, setNote] = useState(item?.note || ''), [reviewed, setReviewed] = useState(item?.reviewed || false), [uncertain, setUncertain] = useState(item?.uncertain || false);
  const [webSources] = useState(item?.webSources || []), [repairConfidence] = useState(item?.repairConfidence), [repairReason] = useState(item?.repairReason || '');
  const [docId, setDocId] = useState(item?.docId || documents[0]?.id || ''), [page, setPage] = useState(item?.page || 1), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function save(e: React.FormEvent) {
    e.preventDefault(); setBusy(true); setError('');
    try { await api(item ? `/items/${item.id}` : '/items', { title, topic, latex, variables, conditions, note, reviewed, uncertain, ...(item ? { webSources, repairConfidence, repairReason } : { docId, page }) }, item ? 'PUT' : 'POST'); await onSaved(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  const changeVariable = (index: number, key: keyof Variable, value: string) => setVariables(current => current.map((v, i) => i === index ? { ...v, [key]: value } : v));
  return <Modal title={item ? 'Check every symbol' : 'Add an equation'} onClose={onClose} wide><p className="modal-intro">Compare with the original page. Equations belong here; conceptual explanations have their own tab.</p>{item && <SourceLink doc={documents.find(d => d.id === item.docId)} page={item.page} />}{repairReason && <div className="repair-summary"><strong>Online suggestion · {repairConfidence} confidence</strong><p>{repairReason}</p>{webSources.length ? <div>{webSources.map(source => <a href={source.url} target="_blank" rel="noreferrer" key={source.url}>{source.title}<ExternalLink size={13} /></a>)}</div> : <small>No usable citation was returned. Keep this entry marked uncertain unless the original page confirms it.</small>}{item?.searchEntryPoint && <div className="google-search-suggestions" dangerouslySetInnerHTML={{ __html: item.searchEntryPoint }} />}</div>}<form onSubmit={save}>
    {!item && <div className="form-grid"><label>Source file<select required value={docId} onChange={e => { setDocId(e.target.value); setPage(1); }}><option value="" disabled>Select a source</option>{documents.map(d => <option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Page / text section<input required type="number" min={1} max={documents.find(d => d.id === docId)?.totalPages || 1} value={page} onChange={e => setPage(Number(e.target.value))} /></label></div>}
    <div className="form-grid"><label>Formula name<input required value={title} onChange={e => setTitle(e.target.value)} placeholder="Angle of friction" /></label><label>Topic<input required value={topic} onChange={e => setTopic(e.target.value)} placeholder="Friction" /></label></div>
    <label className="field-label">LaTeX equation<textarea required className="code-input" value={latex} onChange={e => { setLatex(e.target.value); setReviewed(false); }} rows={3} /></label><p className="fine-print">Use \theta for θ, \sigma for σ, \sum for ∑, and \frac&#123;f&#125;&#123;N&#125; for a fraction. No $ delimiters needed.</p><div className="equation-preview"><span>LIVE PREVIEW</span><MathText latex={latex} block /></div>
    <div className="mini-heading"><h3>What each variable means</h3><button type="button" className="text-button" onClick={() => setVariables([...variables, { symbol: '', meaning: '', unit: '' }])}><Plus size={15} /> Add variable</button></div><div className="variable-editor">{variables.map((v, n) => <div key={n}><input aria-label={`Variable ${n + 1} LaTeX symbol`} required value={v.symbol} placeholder="Symbol (LaTeX)" onChange={e => changeVariable(n, 'symbol', e.target.value)} /><input aria-label={`Variable ${n + 1} meaning`} required value={v.meaning} placeholder="Meaning" onChange={e => changeVariable(n, 'meaning', e.target.value)} /><input aria-label={`Variable ${n + 1} unit`} value={v.unit} placeholder="Unit" onChange={e => changeVariable(n, 'unit', e.target.value)} /><button type="button" className="icon-button" aria-label={`Remove variable ${n + 1}`} onClick={() => setVariables(variables.filter((_, i) => i !== n))}><Trash2 size={15} /></button></div>)}</div>
    <label className="field-label">Conditions / assumptions<textarea value={conditions} onChange={e => setConditions(e.target.value)} rows={2} /></label><label className="field-label">Review notes<textarea value={note} onChange={e => setNote(e.target.value)} rows={2} /></label><label className="check-label"><input type="checkbox" checked={uncertain} onChange={e => { setUncertain(e.target.checked); if (e.target.checked) setReviewed(false); }} />Some notation or definitions are still uncertain</label><label className="check-label"><input type="checkbox" checked={reviewed} disabled={uncertain} onChange={e => setReviewed(e.target.checked)} />I checked this equation and its variable definitions against the source</label>{error && <Status>{error}</Status>}<div className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || !docId}><Check size={16} />{busy ? 'Saving…' : 'Save formula'}</button></div>
  </form></Modal>;
}
