import { useEffect, useId, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronRight, CircleDashed, Clock3, Database, Download, Eye, Layers, LoaderCircle, RotateCcw, Shuffle, Sparkles, Target, TrendingUp, Upload, X } from 'lucide-react';
import { api, Badge, Empty, MathText, Modal, RichText, SourceLink, Status } from './components';
import { SPEX, type Diagram, type Question, type Solution, type Spex, type View } from './types';
import type { SharedProps } from './App';

function EngineeringDiagram({ diagram }: { diagram?: Diagram }) {
  const marker = `arrow-${useId().replace(/:/g, '')}`;
  if (diagram?.image) return <figure className="engineering-diagram source-diagram"><img src={diagram.image.url} alt={diagram.image.alt} loading="lazy" />{diagram.image.caption && <figcaption>{diagram.image.caption}</figcaption>}</figure>;
  if (!diagram || ![...diagram.lines, ...diagram.arrows, ...diagram.circles, ...diagram.rectangles, ...diagram.labels].length) return null;
  const clamp = (value: number) => Math.max(0, Math.min(100, Number.isFinite(value) ? value : 0));
  return <figure className="engineering-diagram" aria-label={diagram.title || 'Problem diagram'}>
    {diagram.title && <strong>{diagram.title}</strong>}
    <svg viewBox="0 0 100 100" role="img" aria-labelledby={`${marker}-title ${marker}-desc`}>
      <title id={`${marker}-title`}>{diagram.title || 'Engineering diagram'}</title><desc id={`${marker}-desc`}>{diagram.caption || 'Diagram accompanying the problem statement'}</desc>
      <defs><marker id={marker} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" /></marker></defs>
      {diagram.rectangles.map((shape, i) => <rect key={`r${i}`} x={clamp(shape.x)} y={clamp(shape.y)} width={clamp(shape.width)} height={clamp(shape.height)} className={shape.filled ? 'filled' : ''} />)}
      {diagram.lines.map((line, i) => <line key={`l${i}`} x1={clamp(line.x1)} y1={clamp(line.y1)} x2={clamp(line.x2)} y2={clamp(line.y2)} className={line.dashed ? 'dashed' : ''} />)}
      {diagram.arrows.map((line, i) => <line key={`a${i}`} x1={clamp(line.x1)} y1={clamp(line.y1)} x2={clamp(line.x2)} y2={clamp(line.y2)} className={line.dashed ? 'diagram-arrow dashed' : 'diagram-arrow'} markerEnd={`url(#${marker})`} />)}
      {diagram.circles.map((shape, i) => <circle key={`c${i}`} cx={clamp(shape.cx)} cy={clamp(shape.cy)} r={Math.max(0, Math.min(50, shape.r))} className={shape.filled ? 'filled' : ''} />)}
      {diagram.labels.map((label, i) => <text key={`t${i}`} x={clamp(label.x)} y={clamp(label.y)} textAnchor={label.align}>{label.text}</text>)}
    </svg>
    {diagram.caption && <figcaption>{diagram.caption}</figcaption>}
  </figure>;
}

export function Practice({ state, refresh, spex, set, notify }: SharedProps) {
  const [generating, setGenerating] = useState(false), [dialog, setDialog] = useState(false), [confirmReplace, setConfirmReplace] = useState(false), [bankDialog, setBankDialog] = useState(false), [error, setError] = useState('');
  const [selected, setSelected] = useState<string | null>(() => localStorage.getItem('civinco-active-problem')), [answer, setAnswer] = useState(''), [solution, setSolution] = useState<Solution | null>(null), [checking, setChecking] = useState(false);
  const questions = [...state.questions].sort((a, b) => a.sourceDocId && a.sourceDocId === b.sourceDocId ? (a.sourcePage || 0) - (b.sourcePage || 0) : b.createdAt.localeCompare(a.createdAt));
  const question = questions.find(q => q.id === selected) || questions[0];
  const attempted = state.attempts.find(a => a.questionId === question?.id);
  useEffect(() => { if (question?.id) localStorage.setItem('civinco-active-problem', question.id); else localStorage.removeItem('civinco-active-problem'); }, [question?.id]);
  useEffect(() => {
    setAnswer(''); setSolution(null); setError('');
    if (question && attempted) {
      setChecking(true);
      api<Solution>(`/questions/${question.id}/solution`, {}).then(setSolution).catch(problem => setError((problem as Error).message)).finally(() => setChecking(false));
    }
  }, [question?.id, Boolean(attempted)]);
  async function check(e?: React.FormEvent, reveal = false) {
    e?.preventDefault(); if (!question) return; setChecking(true); setError('');
    try { const result = reveal ? await api<Solution>(`/questions/${question.id}/solution`, {}) : await api<Solution>(`/questions/${question.id}/answer`, { answer }); setSolution(result); await refresh(); } catch (e) { setError((e as Error).message); } finally { setChecking(false); }
  }
  function next() { const index = questions.findIndex(q => q.id === question.id); setSelected(questions[(index + 1) % questions.length].id); }
  function previous() { const index = questions.findIndex(q => q.id === question.id); setSelected(questions[(index - 1 + questions.length) % questions.length].id); }
  return <><div className="practice-intro"><div><span className="section-kicker"><Target size={16} /> PRACTICE SESSION</span><p>Practice from your materials or start with included examples.</p></div><div className="practice-actions"><button className="button secondary" disabled={generating} onClick={() => setBankDialog(true)}><Database size={16} /> Import problem bank</button><button className="button primary" disabled={generating} onClick={() => questions.length ? setConfirmReplace(true) : setDialog(true)}>{generating ? <LoaderCircle className="spin" size={17} /> : <Sparkles size={17} />}{generating ? 'Generating & checking…' : 'Generate new questions'}</button></div></div>
    {generating && <div className="processing-note"><LoaderCircle className="spin" size={17} /> Preparing the questions and worked solutions. Source problems use one pass; newly generated problems receive an additional solution check.</div>}
    {question && questions.length > 1 && <nav className="practice-navigation" aria-label="Problem navigation"><button className="button secondary" onClick={previous}><ArrowLeft size={16} /> Previous</button><span>{questions.findIndex(q => q.id === question.id) + 1} of {questions.length}</span><button className="button secondary" onClick={next}>Next <ArrowRight size={16} /></button></nav>}
    {!question ? <Empty icon={<Target size={31} />} title="Your next challenge is waiting" text="Import a permanent problem bank, use problems found in your uploaded files, or generate new ones from reviewed formulas." action={<button className="button secondary" onClick={() => setBankDialog(true)}><Database size={16} /> Import a problem bank</button>} /> : <div className="practice-layout"><section className="problem-panel"><div className="problem-meta"><Badge spex={question.spex} set={question.set} /><span>{question.mode === 'sample' ? 'Starter practice' : question.mode === 'bank' ? 'Permanent problem bank · no Gemini usage' : question.mode === 'source' ? 'From your uploaded file · original values' : 'Generated from your materials · checked solution'}</span></div><div className="problem-number">PROBLEM {questions.findIndex(q => q.id === question.id) + 1} OF {questions.length}</div><h2>{question.topic || question.title}</h2><div className="problem-prompt"><RichText text={question.prompt} /></div><EngineeringDiagram diagram={question.diagram} /><div className="answer-section">{!attempted && <form onSubmit={e => check(e)}><label htmlFor="practice-answer">Your answer <span>in {question.unit || 'the specified unit'}</span></label><div className="answer-row"><div className="answer-input"><input id="practice-answer" autoComplete="off" inputMode="decimal" placeholder="Enter your answer" value={answer} onChange={e => setAnswer(e.target.value)} required /><span>{question.unit}</span></div><button className="button primary" disabled={checking || !answer.trim()}>{checking ? 'Checking…' : 'Check answer'}<Check size={17} /></button></div></form>}{!attempted && !solution && <button className="text-button" disabled={checking} onClick={() => check(undefined, true)}><Eye size={15} /> Show solution instead</button>}{attempted && <p className="fine-print">{attempted.revealed ? 'Solution viewed before answering; excluded from accuracy.' : `First attempt: ${attempted.correct ? 'correct' : 'incorrect'}.`}</p>}</div>
      {error && <Status>{error}</Status>}{solution && <div className={`solution-panel ${solution.correct ? 'correct' : solution.revealed ? 'revealed' : 'incorrect'}`}><div className="solution-result">{solution.correct ? <CheckCircle2 size={22} /> : solution.revealed ? <Eye size={22} /> : <RotateCcw size={22} />}<div><h3>{solution.correct ? 'You got it.' : solution.solutionQuality === 'source' ? 'Source context needed.' : solution.revealed ? 'Let’s work through it.' : 'A useful step in learning.'}</h3><p>{solution.correct ? 'Your answer is within the rounding tolerance.' : `Expected answer: ${Number(solution.expected.toFixed(6)).toLocaleString('en-US', { maximumFractionDigits: 6 })} ${solution.unit}`}</p></div></div><h4>{solution.solutionQuality === 'source' ? 'SOURCE REVIEW' : solution.solutionQuality === 'answer-key' ? 'SOURCE ANSWER' : 'WORKED SOLUTION'}</h4>{solution.steps.map((step, index) => <div className="solution-step" key={index}><span>{index + 1}</span><div><p><RichText text={step.text} /></p>{step.latex && <MathText latex={step.latex} block />}</div></div>)}<p className="fine-print">Accepted absolute tolerance: ±{solution.tolerance} {solution.unit}. {question.mode === 'ai' && 'Check AI-generated reasoning against your source if something looks wrong.'}</p>{questions.length > 1 && <button className="button secondary" onClick={next}>Next problem <ArrowRight size={16} /></button>}</div>}
      <div className="problem-sources"><h4>CONNECTED TO YOUR MATERIALS</h4>{question.sourceDocId && <SourceLink doc={state.documents.find(d => d.id === question.sourceDocId)} page={question.sourcePage || 1} />}{question.sourceIds.map(id => { const item = state.items.find(i => i.id === id); return item ? <SourceLink key={id} doc={state.documents.find(d => d.id === item.docId)} page={item.page} /> : null; })}</div>
    </section><aside className="question-list"><div className="mini-heading"><h3>Your questions</h3><span className="count-bubble">{questions.length}</span></div>{questions.map((q, index) => { const attempt = state.attempts.find(a => a.questionId === q.id); return <button key={q.id} onClick={() => setSelected(q.id)} className={q.id === question.id ? 'active' : ''}><span className={`question-status ${attempt?.correct ? 'correct' : ''}`}>{attempt ? attempt.revealed ? <Eye size={15} /> : attempt.correct ? <Check size={16} /> : <X size={15} /> : String(index + 1).padStart(2, '0')}</span><span><strong>{q.title}</strong><small>{SPEX[q.spex].code} · Set {q.set}</small></span><ChevronRight size={14} /></button>; })}</aside></div>}
    {confirmReplace && <Modal title="Replace the current practice set?" onClose={() => setConfirmReplace(false)}><p className="modal-intro">Generating another set will replace the {questions.length} questions currently in Practice. Your completed results will remain in Progress.</p><div className="modal-actions"><button className="button secondary" onClick={() => setConfirmReplace(false)}>Keep current set</button><button className="button primary" onClick={() => { setConfirmReplace(false); setDialog(true); }}>Generate a new set</button></div></Modal>}
    {dialog && <GenerateDialog initialSpex={spex === 'all' ? 'A' : spex} initialSet={set === 'all' ? 1 : Number(set)} connected={state.settings.connected} onClose={() => setDialog(false)} onGenerate={async input => { setGenerating(true); setError(''); try { const result = await api<{ questions: Question[] }>('/questions/generate', { ...(input as object), replace: questions.length > 0 }); await refresh(); setSelected(result.questions[0]?.id || null); setDialog(false); notify(`${result.questions.length} questions are ready.`); } finally { setGenerating(false); } }} />}
    {bankDialog && <ProblemBankDialog onClose={() => setBankDialog(false)} onImported={async result => { await refresh(); setSelected(null); setBankDialog(false); notify(`${result.imported} permanent problem${result.imported === 1 ? '' : 's'} stored. Choose Generate new questions when you want a random set.`); }} />}
  </>;
}

function GenerateDialog({ initialSpex, initialSet, connected, onClose, onGenerate }: { initialSpex: Spex; initialSet: number; connected: boolean; onClose: () => void; onGenerate: (input: unknown) => Promise<void> }) {
  const [spex, setSpex] = useState(initialSpex), [set, setSet] = useState(initialSet), [mode, setMode] = useState('bank'), [style, setStyle] = useState('generated'), [count, setCount] = useState(5), [difficulty, setDifficulty] = useState('Board-level'), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const buttonText = mode === 'bank' ? 'Choose random questions' : mode === 'ai' && style === 'source' ? 'Find source problems' : 'Generate new questions';
  return <Modal title="Create a practice set" onClose={() => { if (!busy) onClose(); }}>
    <p className="modal-intro">Choose where the questions come from, then select an examination and Set.</p>
    <form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await onGenerate({ spex, set, count, mode, style, difficulty }); } catch (problem) { setError((problem as Error).message); } finally { setBusy(false); } }}>
      <label className="field-label">Question source<select value={mode} onChange={e => setMode(e.target.value)}><option value="bank">Permanent problem bank · no Gemini</option><option value="ai">My uploaded materials</option><option value="sample">Starter references · no Gemini</option></select></label>
      {mode === 'ai' && <label className="field-label">Problem type<select value={style} onChange={e => setStyle(e.target.value)}><option value="source">Problems exactly from the uploaded files</option><option value="generated">New problems based on the uploaded files</option></select></label>}
      <div className="form-grid"><label>Examination<select value={spex} onChange={e => setSpex(e.target.value as Spex)}>{(Object.keys(SPEX) as Spex[]).map(s => <option key={s} value={s}>SPEX {s} · {SPEX[s].code}</option>)}</select></label><label>Set<input type="number" min={1} max={999} required value={set} onChange={e => setSet(Number(e.target.value))} /></label></div>
      <div className="form-grid"><label>Number of questions<select value={count} onChange={e => setCount(Number(e.target.value))}>{[3, 5, 10].map(n => <option key={n} value={n}>{n} questions</option>)}</select></label>{mode === 'ai' && <label>Difficulty<select value={difficulty} disabled={style === 'source'} onChange={e => setDifficulty(e.target.value)}>{['Foundation', 'Board-level', 'Challenge'].map(d => <option key={d}>{d}</option>)}</select></label>}</div>
      <p className="fine-print">{mode === 'bank' ? 'Randomly chooses from the permanent bank for this SPEX and Set. No Gemini credits are used.' : mode === 'sample' ? 'Starter questions use randomized numerical examples from Set 1.' : style === 'source' ? 'Uses one Gemini pass to find and solve complete problems already printed in the selected files.' : 'Creates new problems from source-checked equations, then checks every solution.'}</p>
      {mode === 'ai' && !connected && <Status>Connect an API key in AI settings first, or choose a no-Gemini source.</Status>}{error && <Status>{error}</Status>}
      <div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || (mode === 'ai' && !connected)}>{busy ? <LoaderCircle className="spin" size={17} /> : <Sparkles size={17} />}{busy ? 'Preparing questions…' : buttonText}</button></div>
    </form>
  </Modal>;
}

function ProblemBankDialog({ onClose, onImported }: { onClose: () => void; onImported: (result: { imported: number; skipped: number; questions: Question[] }) => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!file) return; setBusy(true); setError('');
    try { const body = new FormData(); body.append('file', file); await onImported(await api<{ imported: number; skipped: number; questions: Question[] }>('/problem-banks', body)); }
    catch (problem) { setError((problem as Error).message); }
    finally { setBusy(false); }
  }
  return <Modal title="Import a permanent problem bank" onClose={() => { if (!busy) onClose(); }}><p className="modal-intro">Import a structured JSON bank directly into this device. No Gemini request is made during import or while studying these problems.</p><a className="button secondary template-download" href="/api/problem-banks/template" download><Download size={16} /> Download JSON template</a><form onSubmit={submit}><label className="problem-bank-picker"><Upload size={24} /><span>{file ? file.name : 'Choose a completed problem-bank JSON file'}</span><input type="file" accept="application/json,.json" required onChange={event => setFile(event.target.files?.[0] || null)} /></label><p className="fine-print">One file represents one SPEX and Set. It may contain up to 5,000 questions and must be 20 MB or smaller. Duplicate questions are skipped.</p>{error && <Status>{error}</Status>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={!file || busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Database size={16} />}{busy ? 'Importing…' : 'Import problem bank'}</button></div></form></Modal>;
}

export function Flashcards({ state, filter, refresh, notify }: SharedProps) {
  const [kind, setKind] = useState('both'), [dueOnly, setDueOnly] = useState(false), [index, setIndex] = useState(0), [flipped, setFlipped] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [shuffle, setShuffle] = useState(0);
  const scoped = filter(state.items);
  const eligible = scoped.filter(i => kind === 'both' || i.kind === kind);
  const cards = useMemo(() => {
    const result = eligible.filter(i => { const review = state.reviews.find(r => r.itemId === i.id); return !dueOnly || !review || new Date(review.due).getTime() <= Date.now(); });
    // Stable shuffle across polling refreshes.
    const score = (id: string) => [...id].reduce((s, c) => ((s * 31 + c.charCodeAt(0)) ^ shuffle) >>> 0, shuffle + 1);
    return shuffle ? result.sort((a, b) => score(a.id) - score(b.id)) : result;
  }, [JSON.stringify(eligible), JSON.stringify(state.reviews), dueOnly, shuffle]);
  const card = cards[index % Math.max(cards.length, 1)];
  useEffect(() => { setFlipped(false); setError(''); }, [card?.id]);
  const due = eligible.filter(i => { const review = state.reviews.find(r => r.itemId === i.id); return !review || new Date(review.due).getTime() <= Date.now(); }).length;
  async function rate(rating: string) { if (!card) return; setBusy(true); setError(''); try { await api('/reviews', { itemId: card.id, rating }); await refresh(); if (!dueOnly) setIndex(index + 1); setFlipped(false); notify(rating === 'again' ? 'Scheduled again in 10 minutes.' : 'Review saved. Your next review is scheduled.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><div className="flash-toolbar"><div className="segmented">{[['both', 'Mixed deck'], ['concept', 'Concepts'], ['formula', 'Equations']].map(([id, label]) => <button key={id} className={kind === id ? 'active' : ''} onClick={() => { setKind(id); setIndex(0); }}>{label}</button>)}</div><label className="check-label"><input type="checkbox" checked={dueOnly} onChange={e => { setDueOnly(e.target.checked); setIndex(0); }} />Due for review only <span className="count-bubble">{due}</span></label><button className="button secondary" onClick={() => { setShuffle(shuffle + 1); setIndex(0); }}><Shuffle size={16} /> Shuffle</button></div>
    {!card ? <Empty icon={<Layers size={30} />} title={dueOnly && eligible.length ? 'All caught up for now.' : 'Let’s build your first deck.'} text={dueOnly && eligible.length ? 'Your next cards will appear when they’re due. Turn off “Due for review only” to browse the whole deck.' : 'Extract concepts or equations, or add starter references from Home. Your study entries become flashcards automatically.'} /> : <div className="flash-workspace"><div className="flash-progress"><span>{card.kind === 'formula' ? 'EQUATION RECALL' : 'CONCEPT RECALL'}</span><span>{index % cards.length + 1} / {cards.length} cards</span></div><button className={`flashcard ${flipped ? 'flipped' : ''}`} onClick={() => setFlipped(!flipped)} aria-label={flipped ? 'Show question side' : 'Reveal flashcard answer'}><div className="flashcard-meta"><Badge spex={card.spex} set={card.set} /><span>{card.topic}</span>{card.kind === 'formula' && (!card.reviewed || card.uncertain) && <span className="flashcard-source-warning">SOURCE CHECK PENDING</span>}</div><div className="flashcard-content"><span className="eyebrow">{flipped ? 'THE ANSWER' : card.kind === 'formula' ? 'CAN YOU RECALL THE EQUATION?' : 'EXPLAIN THIS IN YOUR OWN WORDS'}</span><h2>{card.title}</h2>{flipped ? card.kind === 'formula' ? <><MathText latex={card.latex || ''} block /><div className="flash-variables">{card.variables?.map((v, n) => <p key={n}><MathText latex={v.symbol} /> <span>— {v.meaning}{v.unit && ` (${v.unit})`}</span></p>)}</div><p className="flash-conditions">{card.conditions}</p></> : <p className="flash-explanation"><RichText text={card.explanation || ''} /></p> : <span className="flash-symbol">{card.kind === 'formula' ? 'ƒ' : '“'}</span>}</div><span className="flip-hint"><RotateCcw size={14} />{flipped ? 'Click to return to the question' : 'Think it through, then click to reveal'}</span></button><SourceLink doc={state.documents.find(d => d.id === card.docId)} page={card.page} />
      {flipped ? <div className="recall-rating"><p>How well did you remember?</p><div>{[['again', 'Again', '10 min'], ['hard', 'Hard', '1 day'], ['good', 'Good', 'Spaced review'], ['easy', 'Easy', 'Longer interval']].map(([id, label, time]) => <button className={`rating ${id}`} key={id} disabled={busy} onClick={() => rate(id)}><strong>{label}</strong><small>{time}</small></button>)}</div></div> : <div className="flash-navigation"><button className="button secondary" onClick={() => setIndex((index + cards.length - 1) % cards.length)}><ArrowLeft size={16} /> Previous</button><span>Take your time. Recall is the work.</span><button className="button secondary" onClick={() => setIndex(index + 1)}>Skip <ArrowRight size={16} /></button></div>}
    </div>}{error && <Status>{error}</Status>}{scoped.some(i => i.kind === 'formula' && (!i.reviewed || i.uncertain)) && <p className="fine-print centered">Unchecked equations are included for study and marked “Source check pending.” Verify uncertain symbols in Concepts & Formulas before relying on them.</p>}
  </>;
}

export function Progress({ state, filter, navigate }: SharedProps & { navigate: (view: View) => void }) {
  const attempts = filter(state.attempts), scored = attempts.filter(a => !a.revealed), correct = scored.filter(a => a.correct).length;
  const reviews = filter(state.reviews), accuracy = scored.length ? Math.round(correct / scored.length * 100) : null;
  const topics = [...new Set(scored.map(a => a.topic))].map(topic => { const attempts = scored.filter(a => a.topic === topic); return { topic, count: attempts.length, correct: attempts.filter(a => a.correct).length, percent: Math.round(attempts.filter(a => a.correct).length / attempts.length * 100) }; }).sort((a, b) => a.percent - b.percent);
  const days = Array.from({ length: 7 }, (_, n) => { const day = new Date(); day.setDate(day.getDate() - 6 + n); const date = day.toLocaleDateString('en-CA'); const count = attempts.filter(a => new Date(a.createdAt).toLocaleDateString('en-CA') === date).length; return { label: day.toLocaleDateString('en-US', { weekday: 'short' }), count }; });
  const max = Math.max(3, ...days.map(d => d.count));
  return <><div className="progress-stats">{[{ icon: Target, value: scored.length, title: 'Problems attempted', note: 'First answers only' }, { icon: CheckCircle2, value: accuracy === null ? '—' : `${accuracy}%`, title: 'First-attempt accuracy', note: `${correct} correct · ${attempts.filter(a => a.revealed).length} solutions viewed` }, { icon: Layers, value: reviews.reduce((sum, r) => sum + r.count, 0), title: 'Flashcard reviews', note: `${reviews.length} different cards` }, { icon: TrendingUp, value: topics.filter(t => t.count >= 3 && t.percent >= 80).length, title: 'Strong topics', note: '≥80% with 3+ attempts' }].map(({ icon: Icon, value, title, note }) => <div className="progress-stat" key={title}><Icon size={22} /><strong>{value}</strong><span>{title}</span><small>{note}</small></div>)}</div>
    {!scored.length && <div className="starter-banner"><span className="starter-icon"><TrendingUp size={24} /></span><div><strong>Your story is just getting started.</strong><p>Solve a few problems to start discovering your strengths and next areas to review.</p></div><button className="button secondary" onClick={() => navigate('practice')}>Start practicing <ArrowRight size={15} /></button></div>}
    <div className="progress-grid"><section className="panel"><div className="section-title"><div><h2>Your review rhythm</h2><p>Problems attempted or explored over the last 7 days.</p></div><Clock3 size={20} /></div><div className="activity-chart" role="img" aria-label={days.map(d => `${d.label}: ${d.count} problems`).join(', ')}>{days.map((day, n) => <div className="activity-day" key={n}><strong>{day.count}</strong><div className="bar-area"><span style={{ height: `${Math.max(3, day.count / max * 100)}%` }} className={day.count ? 'filled' : ''} /></div><small>{day.label}</small></div>)}</div></section><section className="panel"><div className="section-title"><div><h2>Across your examinations</h2><p>Confidence comes from consistent practice.</p></div></div><div className="exam-progress">{(Object.keys(SPEX) as Spex[]).map(s => { const subset = scored.filter(a => a.spex === s), percentage = subset.length ? Math.round(subset.filter(a => a.correct).length / subset.length * 100) : 0; return <div key={s}><div><Badge spex={s} /><strong>{subset.length ? `${percentage}%` : 'No attempts yet'}</strong></div><div className={`progress-track ${SPEX[s].color}`}><span style={{ width: `${percentage}%` }} /></div><small>{subset.length} first attempts</small></div>; })}</div></section></div>
    <section className="panel topic-progress"><div className="section-title"><div><h2>Where to focus next</h2><p>Based on your first attempts. Three or more per topic give a useful starting signal.</p></div><span className="subtle-label">TOPIC BREAKDOWN</span></div>{!topics.length ? <Empty icon={<CircleDashed size={25} />} title="The picture gets clearer with practice." text="Your topic strengths and review priorities will appear here." /> : <div className="topic-table">{topics.map(topic => <div className="topic-row" key={topic.topic}><div><strong>{topic.topic}</strong><small>{topic.count} {topic.count === 1 ? 'attempt' : 'attempts'} · {topic.correct} correct</small></div><div className="topic-bar"><div className="progress-track"><span style={{ width: `${topic.percent}%` }} /></div><strong>{topic.percent}%</strong></div><span className={`topic-signal ${topic.count < 3 ? 'learning' : topic.percent >= 80 ? 'strong' : topic.percent < 60 ? 'focus' : 'building'}`}>{topic.count < 3 ? 'Keep exploring' : topic.percent >= 80 ? 'Looking strong' : topic.percent < 60 ? 'Focus here next' : 'Building confidence'}</span></div>)}</div>}</section><p className="fine-print centered">Progress reflects practice in this app, not a prediction of board-exam performance. Viewing a solution before answering is excluded from accuracy.</p>
  </>;
}
