import { useEffect, useId, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, Check, CheckCircle2, ChevronRight, CircleDashed, Clock3, Eye, Layers, LoaderCircle, RotateCcw, Shuffle, Sparkles, Target, TrendingUp, X } from 'lucide-react';
import { api, Badge, Empty, MathText, Modal, RichText, SourceLink, Status } from './components';
import { SPEX, type Diagram, type Question, type Solution, type Spex, type View } from './types';
import type { SharedProps } from './App';

function EngineeringDiagram({ diagram }: { diagram?: Diagram }) {
  const marker = `arrow-${useId().replace(/:/g, '')}`;
  if (!diagram || ![...diagram.lines, ...diagram.arrows, ...diagram.circles, ...diagram.rectangles, ...diagram.labels].length) return null;
  const clamp = (value: number) => Math.max(0, Math.min(100, Number.isFinite(value) ? value : 0));
  return <figure className="engineering-diagram" aria-label={diagram.title || 'Problem diagram'}>
    {diagram.title && <strong>{diagram.title}</strong>}
    <svg viewBox="0 0 100 100" role="img" aria-labelledby={`${marker}-title ${marker}-desc`}>
      <title id={`${marker}-title`}>{diagram.title || 'Engineering diagram'}</title><desc id={`${marker}-desc`}>{diagram.caption || 'Diagram accompanying the problem statement'}</desc>
      <defs><marker id={marker} viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" /></marker></defs>
      {diagram.rectangles.map((shape, i) => <rect key={`r${i}`} x={clamp(shape.x)} y={clamp(shape.y)} width={clamp(shape.width)} height={clamp(shape.height)} className={shape.filled ? 'filled' : ''} />)}
      {diagram.lines.map((line, i) => <line key={`l${i}`} x1={clamp(line.x1)} y1={clamp(line.y1)} x2={clamp(line.x2)} y2={clamp(line.y2)} className={line.dashed ? 'dashed' : ''} />)}
      {diagram.arrows.map((line, i) => <line key={`a${i}`} x1={clamp(line.x1)} y1={clamp(line.y1)} x2={clamp(line.x2)} y2={clamp(line.y2)} className={line.dashed ? 'diagram-arrow dashed' : 'diagram-arrow'} markerEnd={`url(#${marker})`} />)}
      {diagram.circles.map((shape, i) => <circle key={`c${i}`} cx={clamp(shape.cx)} cy={clamp(shape.cy)} r={Math.max(0, Math.min(50, shape.r))} className={shape.filled ? 'filled' : ''} />)}
      {diagram.labels.map((label, i) => <text key={`t${i}`} x={clamp(label.x)} y={clamp(label.y)} textAnchor={label.align}>{label.text}</text>)}
    </svg>
    {diagram.caption && <figcaption>{diagram.caption}</figcaption>}
  </figure>;
}

export function Practice({ state, filter, refresh, spex, set, notify }: SharedProps) {
  const [generating, setGenerating] = useState(false), [dialog, setDialog] = useState(false), [error, setError] = useState('');
  const [selected, setSelected] = useState<string | null>(null), [answer, setAnswer] = useState(''), [solution, setSolution] = useState<Solution | null>(null), [checking, setChecking] = useState(false);
  const questions = filter(state.questions).sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  const question = questions.find(q => q.id === selected) || questions[0];
  const attempted = state.attempts.find(a => a.questionId === question?.id);
  useEffect(() => { setAnswer(''); setSolution(null); setError(''); }, [question?.id]);
  async function check(e?: React.FormEvent, reveal = false) {
    e?.preventDefault(); if (!question) return; setChecking(true); setError('');
    try { const result = reveal ? await api<Solution>(`/questions/${question.id}/solution`, {}) : await api<Solution>(`/questions/${question.id}/answer`, { answer }); setSolution(result); await refresh(); } catch (e) { setError((e as Error).message); } finally { setChecking(false); }
  }
  function next() { const index = questions.findIndex(q => q.id === question.id); setSelected(questions[(index + 1) % questions.length].id); }
  return <><div className="practice-intro"><div><span className="section-kicker"><Target size={16} /> YOUR PROBLEM-SOLVING WORKBENCH</span><p>Practice from your materials or start with included examples.</p></div><button className="button primary" disabled={generating} onClick={() => setDialog(true)}>{generating ? <LoaderCircle className="spin" size={17} /> : <Sparkles size={17} />}{generating ? 'Generating & checking…' : 'Generate new questions'}</button></div>
    {generating && <div className="processing-note"><LoaderCircle className="spin" size={17} /> Creating a fresh set and independently checking the worked solutions. This may take a few minutes.</div>}
    {!question ? <Empty icon={<Target size={31} />} title="Your next challenge is waiting" text="Generate a question set from reviewed formulas in your uploaded files, or try the starter questions without an API key." action={<button className="button secondary" onClick={() => setDialog(true)}><Sparkles size={16} /> Create a practice set</button>} /> : <div className="practice-layout"><section className="problem-panel"><div className="problem-meta"><Badge spex={question.spex} set={question.set} /><span>{question.mode === 'sample' ? 'Starter practice' : 'AI-generated · solution audited'}</span></div><div className="problem-number">PROBLEM {questions.findIndex(q => q.id === question.id) + 1} OF {questions.length}</div><h2>{question.title}</h2><div className="problem-prompt"><RichText text={question.prompt} /></div><EngineeringDiagram diagram={question.diagram} /><div className="answer-section"><form onSubmit={e => check(e)}><label htmlFor="practice-answer">Your answer <span>in {question.unit || 'the specified unit'}</span></label><div className="answer-row"><div className="answer-input"><input id="practice-answer" autoComplete="off" inputMode="decimal" placeholder="Enter your answer" value={answer} onChange={e => setAnswer(e.target.value)} required /><span>{question.unit}</span></div><button className="button primary" disabled={checking || !answer.trim()}>{checking ? 'Checking…' : 'Check answer'}<Check size={17} /></button></div></form>{!solution && <button className="text-button" disabled={checking} onClick={() => check(undefined, true)}><Eye size={15} /> {attempted ? 'View worked solution' : 'Show solution instead'}</button>}{attempted && <p className="fine-print">{attempted.revealed ? 'Solution viewed before answering; excluded from accuracy.' : `First attempt: ${attempted.correct ? 'correct' : 'incorrect'}.`}</p>}</div>
      {error && <Status>{error}</Status>}{solution && <div className={`solution-panel ${solution.correct ? 'correct' : solution.revealed ? 'revealed' : 'incorrect'}`}><div className="solution-result">{solution.correct ? <CheckCircle2 size={22} /> : solution.revealed ? <Eye size={22} /> : <RotateCcw size={22} />}<div><h3>{solution.correct ? 'You got it.' : solution.revealed ? 'Let’s work through it.' : 'A useful step in learning.'}</h3><p>{solution.correct ? 'Your answer is within the rounding tolerance.' : `Expected answer: ${Number(solution.expected.toFixed(6)).toLocaleString('en-US', { maximumFractionDigits: 6 })} ${solution.unit}`}</p></div></div><h4>WORKED SOLUTION</h4>{solution.steps.map((step, index) => <div className="solution-step" key={index}><span>{index + 1}</span><div><p><RichText text={step.text} /></p>{step.latex && <MathText latex={step.latex} block />}</div></div>)}<p className="fine-print">Accepted absolute tolerance: ±{solution.tolerance} {solution.unit}. {question.mode === 'ai' && 'Check AI-generated reasoning against your source if something looks wrong.'}</p>{questions.length > 1 && <button className="button secondary" onClick={next}>Next problem <ArrowRight size={16} /></button>}</div>}
      <div className="problem-sources"><h4>CONNECTED TO YOUR MATERIALS</h4>{question.sourceIds.map(id => { const item = state.items.find(i => i.id === id); return item ? <SourceLink key={id} doc={state.documents.find(d => d.id === item.docId)} page={item.page} /> : null; })}</div>
    </section><aside className="question-list"><div className="mini-heading"><h3>Your questions</h3><span className="count-bubble">{questions.length}</span></div>{questions.map((q, index) => { const attempt = state.attempts.find(a => a.questionId === q.id); return <button key={q.id} onClick={() => setSelected(q.id)} className={q.id === question.id ? 'active' : ''}><span className={`question-status ${attempt?.correct ? 'correct' : ''}`}>{attempt ? attempt.revealed ? <Eye size={15} /> : attempt.correct ? <Check size={16} /> : <X size={15} /> : String(index + 1).padStart(2, '0')}</span><span><strong>{q.title}</strong><small>{SPEX[q.spex].code} · Set {q.set}</small></span><ChevronRight size={14} /></button>; })}</aside></div>}
    {dialog && <GenerateDialog initialSpex={spex === 'all' ? 'A' : spex} initialSet={set === 'all' ? 1 : Number(set)} connected={state.settings.connected} onClose={() => setDialog(false)} onGenerate={async input => { setGenerating(true); setError(''); try { const result = await api<{ questions: Question[] }>('/questions/generate', input); await refresh(); setSelected(result.questions[0]?.id || null); setDialog(false); notify(`${result.questions.length} new questions are ready. Change the SPEX/Set filter if needed.`); } finally { setGenerating(false); } }} />}
  </>;
}

function GenerateDialog({ initialSpex, initialSet, connected, onClose, onGenerate }: { initialSpex: Spex; initialSet: number; connected: boolean; onClose: () => void; onGenerate: (input: unknown) => Promise<void> }) {
  const [spex, setSpex] = useState(initialSpex), [set, setSet] = useState(initialSet), [mode, setMode] = useState(connected ? 'ai' : 'sample'), [count, setCount] = useState(5), [difficulty, setDifficulty] = useState('Board-level'), [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <Modal title="A fresh set of challenges" onClose={() => { if (!busy) onClose(); }}><p className="modal-intro">Choose an examination and Set. Your new questions will be saved so you can return to them.</p><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { await onGenerate({ spex, set, count, mode, difficulty }); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><label className="field-label">Question source<select value={mode} onChange={e => setMode(e.target.value)}><option value="ai">My uploaded materials · AI</option><option value="sample">Starter references · no API key needed</option></select></label><div className="form-grid"><label>Examination<select value={spex} onChange={e => setSpex(e.target.value as Spex)}>{(Object.keys(SPEX) as Spex[]).map(s => <option key={s} value={s}>SPEX {s} · {SPEX[s].code}</option>)}</select></label><label>Set<input type="number" min={1} max={999} required value={set} onChange={e => setSet(Number(e.target.value))} /></label></div><div className="form-grid"><label>Number of questions<select value={count} onChange={e => setCount(Number(e.target.value))}>{[3, 5, 10].map(n => <option key={n} value={n}>{n} questions</option>)}</select></label><label>Difficulty<select value={difficulty} disabled={mode === 'sample'} onChange={e => setDifficulty(e.target.value)}>{['Foundation', 'Board-level', 'Challenge'].map(d => <option key={d}>{d}</option>)}</select></label></div><p className="fine-print">{mode === 'sample' ? 'Starter questions use randomized numerical examples from Set 1. Add starter references on Home first.' : 'Uses concepts and source-checked equations in this SPEX and Set. Generated solutions get a second AI check before they are saved.'}</p>{mode === 'ai' && !connected && <Status>Connect an API key in AI settings first, or choose starter references.</Status>}{error && <Status>{error}</Status>}<div className="modal-actions"><button type="button" className="button secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || (mode === 'ai' && !connected)}>{busy ? <LoaderCircle className="spin" size={17} /> : <Sparkles size={17} />}{busy ? 'Generating & checking…' : 'Generate new questions'}</button></div></form></Modal>;
}

export function Flashcards({ state, filter, refresh, notify }: SharedProps) {
  const [kind, setKind] = useState('both'), [dueOnly, setDueOnly] = useState(false), [index, setIndex] = useState(0), [flipped, setFlipped] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [shuffle, setShuffle] = useState(0);
  const scoped = filter(state.items);
  const eligible = scoped.filter(i => (kind === 'both' || i.kind === kind) && (i.kind !== 'formula' || (i.reviewed && !i.uncertain)));
  const cards = useMemo(() => {
    const result = eligible.filter(i => { const review = state.reviews.find(r => r.itemId === i.id); return !dueOnly || !review || new Date(review.due).getTime() <= Date.now(); });
    // Stable shuffle across polling refreshes.
    const score = (id: string) => [...id].reduce((s, c) => ((s * 31 + c.charCodeAt(0)) ^ shuffle) >>> 0, shuffle + 1);
    return shuffle ? result.sort((a, b) => score(a.id) - score(b.id)) : result;
  }, [JSON.stringify(eligible), JSON.stringify(state.reviews), dueOnly, shuffle]);
  const card = cards[index % Math.max(cards.length, 1)];
  useEffect(() => { setFlipped(false); setError(''); }, [card?.id]);
  const due = eligible.filter(i => { const review = state.reviews.find(r => r.itemId === i.id); return !review || new Date(review.due).getTime() <= Date.now(); }).length;
  async function rate(rating: string) { if (!card) return; setBusy(true); setError(''); try { await api('/reviews', { itemId: card.id, rating }); await refresh(); if (!dueOnly) setIndex(index + 1); setFlipped(false); notify(rating === 'again' ? 'Scheduled again in 10 minutes.' : 'Review saved. Your next review is scheduled.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><div className="flash-toolbar"><div className="segmented">{[['both', 'Mixed deck'], ['concept', 'Concepts'], ['formula', 'Equations']].map(([id, label]) => <button key={id} className={kind === id ? 'active' : ''} onClick={() => { setKind(id); setIndex(0); }}>{label}</button>)}</div><label className="check-label"><input type="checkbox" checked={dueOnly} onChange={e => { setDueOnly(e.target.checked); setIndex(0); }} />Due for review only <span className="count-bubble">{due}</span></label><button className="button secondary" onClick={() => { setShuffle(shuffle + 1); setIndex(0); }}><Shuffle size={16} /> Shuffle</button></div>
    {!card ? <Empty icon={<Layers size={30} />} title={dueOnly && eligible.length ? 'All caught up for now.' : 'Let’s build your first deck.'} text={dueOnly && eligible.length ? 'Your next cards will appear when they’re due. Turn off “Due for review only” to browse the whole deck.' : 'Extract concepts and approve formula notation, or add starter references from Home. Your study entries become flashcards automatically.'} /> : <div className="flash-workspace"><div className="flash-progress"><span>{card.kind === 'formula' ? 'EQUATION RECALL' : 'CONCEPT RECALL'}</span><span>{index % cards.length + 1} / {cards.length} cards</span></div><button className={`flashcard ${flipped ? 'flipped' : ''}`} onClick={() => setFlipped(!flipped)} aria-label={flipped ? 'Show question side' : 'Reveal flashcard answer'}><div className="flashcard-meta"><Badge spex={card.spex} set={card.set} /><span>{card.topic}</span></div><div className="flashcard-content"><span className="eyebrow">{flipped ? 'THE ANSWER' : card.kind === 'formula' ? 'CAN YOU RECALL THE EQUATION?' : 'EXPLAIN THIS IN YOUR OWN WORDS'}</span><h2>{card.title}</h2>{flipped ? card.kind === 'formula' ? <><MathText latex={card.latex || ''} block /><div className="flash-variables">{card.variables?.map((v, n) => <p key={n}><MathText latex={v.symbol} /> <span>— {v.meaning}{v.unit && ` (${v.unit})`}</span></p>)}</div><p className="flash-conditions">{card.conditions}</p></> : <p className="flash-explanation"><RichText text={card.explanation || ''} /></p> : <span className="flash-symbol">{card.kind === 'formula' ? 'ƒ' : '“'}</span>}</div><span className="flip-hint"><RotateCcw size={14} />{flipped ? 'Click to return to the question' : 'Think it through, then click to reveal'}</span></button><SourceLink doc={state.documents.find(d => d.id === card.docId)} page={card.page} />
      {flipped ? <div className="recall-rating"><p>How well did you remember?</p><div>{[['again', 'Again', '10 min'], ['hard', 'Hard', '1 day'], ['good', 'Good', 'Spaced review'], ['easy', 'Easy', 'Longer interval']].map(([id, label, time]) => <button className={`rating ${id}`} key={id} disabled={busy} onClick={() => rate(id)}><strong>{label}</strong><small>{time}</small></button>)}</div></div> : <div className="flash-navigation"><button className="button secondary" onClick={() => setIndex((index + cards.length - 1) % cards.length)}><ArrowLeft size={16} /> Previous</button><span>Take your time. Recall is the work.</span><button className="button secondary" onClick={() => setIndex(index + 1)}>Skip <ArrowRight size={16} /></button></div>}
    </div>}{error && <Status>{error}</Status>}{scoped.some(i => i.kind === 'formula' && (!i.reviewed || i.uncertain)) && <p className="fine-print centered">Equations with unchecked or uncertain symbols stay out of the deck until you approve them in Concepts & Formulas.</p>}
  </>;
}

export function Progress({ state, filter, navigate }: SharedProps & { navigate: (view: View) => void }) {
  const attempts = filter(state.attempts), scored = attempts.filter(a => !a.revealed), correct = scored.filter(a => a.correct).length;
  const reviews = filter(state.reviews), accuracy = scored.length ? Math.round(correct / scored.length * 100) : null;
  const topics = [...new Set(scored.map(a => a.topic))].map(topic => { const attempts = scored.filter(a => a.topic === topic); return { topic, count: attempts.length, correct: attempts.filter(a => a.correct).length, percent: Math.round(attempts.filter(a => a.correct).length / attempts.length * 100) }; }).sort((a, b) => a.percent - b.percent);
  const days = Array.from({ length: 7 }, (_, n) => { const day = new Date(); day.setDate(day.getDate() - 6 + n); const date = day.toLocaleDateString('en-CA'); const count = attempts.filter(a => new Date(a.createdAt).toLocaleDateString('en-CA') === date).length; return { label: day.toLocaleDateString('en-US', { weekday: 'short' }), count }; });
  const max = Math.max(3, ...days.map(d => d.count));
  return <><div className="progress-stats">{[{ icon: Target, value: scored.length, title: 'Problems attempted', note: 'First answers only' }, { icon: CheckCircle2, value: accuracy === null ? '—' : `${accuracy}%`, title: 'First-attempt accuracy', note: `${correct} correct · ${attempts.filter(a => a.revealed).length} solutions viewed` }, { icon: Layers, value: reviews.reduce((sum, r) => sum + r.count, 0), title: 'Flashcard reviews', note: `${reviews.length} different cards` }, { icon: TrendingUp, value: topics.filter(t => t.count >= 3 && t.percent >= 80).length, title: 'Strong topics', note: '≥80% with 3+ attempts' }].map(({ icon: Icon, value, title, note }) => <div className="progress-stat" key={title}><Icon size={22} /><strong>{value}</strong><span>{title}</span><small>{note}</small></div>)}</div>
    {!scored.length && <div className="starter-banner"><span className="starter-icon"><TrendingUp size={24} /></span><div><strong>Your story is just getting started.</strong><p>Solve a few problems to start discovering your strengths and next areas to review.</p></div><button className="button secondary" onClick={() => navigate('practice')}>Start practicing <ArrowRight size={15} /></button></div>}
    <div className="progress-grid"><section className="panel"><div className="section-title"><div><h2>Your review rhythm</h2><p>Problems attempted or explored over the last 7 days.</p></div><Clock3 size={20} /></div><div className="activity-chart" role="img" aria-label={days.map(d => `${d.label}: ${d.count} problems`).join(', ')}>{days.map((day, n) => <div className="activity-day" key={n}><strong>{day.count}</strong><div className="bar-area"><span style={{ height: `${Math.max(3, day.count / max * 100)}%` }} className={day.count ? 'filled' : ''} /></div><small>{day.label}</small></div>)}</div></section><section className="panel"><div className="section-title"><div><h2>Across your examinations</h2><p>Confidence comes from consistent practice.</p></div></div><div className="exam-progress">{(Object.keys(SPEX) as Spex[]).map(s => { const subset = scored.filter(a => a.spex === s), percentage = subset.length ? Math.round(subset.filter(a => a.correct).length / subset.length * 100) : 0; return <div key={s}><div><Badge spex={s} /><strong>{subset.length ? `${percentage}%` : 'No attempts yet'}</strong></div><div className={`progress-track ${SPEX[s].color}`}><span style={{ width: `${percentage}%` }} /></div><small>{subset.length} first attempts</small></div>; })}</div></section></div>
    <section className="panel topic-progress"><div className="section-title"><div><h2>Where to focus next</h2><p>Based on your first attempts. Three or more per topic give a useful starting signal.</p></div><span className="subtle-label">TOPIC BREAKDOWN</span></div>{!topics.length ? <Empty icon={<CircleDashed size={25} />} title="The picture gets clearer with practice." text="Your topic strengths and review priorities will appear here." /> : <div className="topic-table">{topics.map(topic => <div className="topic-row" key={topic.topic}><div><strong>{topic.topic}</strong><small>{topic.count} {topic.count === 1 ? 'attempt' : 'attempts'} · {topic.correct} correct</small></div><div className="topic-bar"><div className="progress-track"><span style={{ width: `${topic.percent}%` }} /></div><strong>{topic.percent}%</strong></div><span className={`topic-signal ${topic.count < 3 ? 'learning' : topic.percent >= 80 ? 'strong' : topic.percent < 60 ? 'focus' : 'building'}`}>{topic.count < 3 ? 'Keep exploring' : topic.percent >= 80 ? 'Looking strong' : topic.percent < 60 ? 'Focus here next' : 'Building confidence'}</span></div>)}</div>}</section><p className="fine-print centered">Progress reflects practice in this app, not a prediction of board-exam performance. Viewing a solution before answering is excluded from accuracy.</p>
  </>;
}
